name: CI

on:
  push:
    branches:
      - '**'
    paths:
      - 'system/**'
      - 'templates/**'
    tags-ignore:
      - '**'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint
    env:
      GOFLAGS: -buildvcs=false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run linter
        run: golangci-lint run

  unit-test:
    runs-on: ubuntu-latest
    container: golang:bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests
        run: go test -v --cover ./system