name: Release

on:
  create:
    tags:
      - 'v[0-9]+.[0-9]+'

jobs:
  binary-release:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/christiantragesser/gitlab-ci-templates/intermodal:github
    env:
      GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Binary releases
        run: |
          /usr/bin/git config --global --add safe.directory /__w/waia/waia
          goreleaser release